insert into genre (id, name, parent_id, slug) values (1, 'Лёгкое чтение', null, 'genre-bmf-697');
insert into genre (id, name, parent_id, slug) values (2, 'Фантастика', 1, 'genre-eke-040');
insert into genre (id, name, parent_id, slug) values (3, 'Боевики', 1, 'genre-ooc-354');
insert into genre (id, name, parent_id, slug) values (4, 'Детективы', 1, 'genre-pam-818');
insert into genre (id, name, parent_id, slug) values (5, 'Триллер', 4, 'genre-swb-686');
insert into genre (id, name, parent_id, slug) values (6, 'Крутой детектив', 4, 'genre-pmy-944');
insert into genre (id, name, parent_id, slug) values (7, 'Иронический детектив', 4, 'genre-woq-159');
insert into genre (id, name, parent_id, slug) values (8, 'Про маньяков', 4, 'genre-rpy-293');
insert into genre (id, name, parent_id, slug) values (9, 'Шпионский детектив', 4, 'genre-kct-498');
insert into genre (id, name, parent_id, slug) values (10, 'Криминальный детектив', 4, 'genre-rbe-176');
insert into genre (id, name, parent_id, slug) values (11, 'Классический детектив', 4, 'genre-moj-775');
insert into genre (id, name, parent_id, slug) values (12, 'Политический детектив', 4, 'genre-ceu-992');
insert into genre (id, name, parent_id, slug) values (13, 'Фэнтези', 1, 'genre-nxy-003');
insert into genre (id, name, parent_id, slug) values (14, 'Романы', 1, 'genre-zus-880');
insert into genre (id, name, parent_id, slug) values (15, 'Ужасы', 1, 'genre-xhz-136');
insert into genre (id, name, parent_id, slug) values (16, 'Приключения', 1, 'genre-jmc-457');
insert into genre (id, name, parent_id, slug) values (17, 'Серьёзное чтение', null, 'genre-dpb-255');
insert into genre (id, name, parent_id, slug) values (18, 'Биографии', 1, 'genre-dfv-164');
insert into genre (id, name, parent_id, slug) values (19, 'Деловая литература', null, 'genre-rcd-552');
insert into genre (id, name, parent_id, slug) values (20, 'Деловая литература', 19, 'genre-dsw-632');
insert into genre (id, name, parent_id, slug) values (21, 'Управление экономикой', 19, 'genre-tqd-865');
insert into genre (id, name, parent_id, slug) values (22, 'Карьера', 19, 'genre-kdi-840');
insert into genre (id, name, parent_id, slug) values (23, 'Маркетинг, PR, реклама', 19, 'genre-uvz-864');
insert into genre (id, name, parent_id, slug) values (24, 'Финансы', 19, 'genre-imn-720');
insert into genre (id, name, parent_id, slug) values (25, 'Бизнес-справочники', 19, 'genre-gno-231');
insert into genre (id, name, parent_id, slug) values (26, 'Личные финансы', 19, 'genre-sfs-964');
insert into genre (id, name, parent_id, slug) values (27, 'Менеджмент', 19, 'genre-ipz-239');
insert into genre (id, name, parent_id, slug) values (28, 'Зарубежная деловая литература', 19, 'genre-nbm-043');
insert into genre (id, name, parent_id, slug) values (29, 'Личная эффективность', 19, 'genre-ozm-158');
insert into genre (id, name, parent_id, slug) values (30, 'Тайм-менеджмент', 19, 'genre-dbn-839');
insert into genre (id, name, parent_id, slug) values (31, 'Малый бизнес', 19, 'genre-xad-686');
insert into genre (id, name, parent_id, slug) values (32, 'Продажи', 19, 'genre-onc-520');
insert into genre (id, name, parent_id, slug) values (33, 'Стартапы и создание бизнеса', 19, 'genre-zew-572');
insert into genre (id, name, parent_id, slug) values (34, 'Корпоративная культура', 19, 'genre-efi-028');
insert into genre (id, name, parent_id, slug) values (35, 'Банковское дело', 19, 'genre-qhf-411');
insert into genre (id, name, parent_id, slug) values (36, 'Логистика', 19, 'genre-icx-996');
insert into genre (id, name, parent_id, slug) values (37, 'Драматургия', null, 'genre-zji-642');
insert into genre (id, name, parent_id, slug) values (38, 'Античная драма', 37, 'genre-ajp-956');
insert into genre (id, name, parent_id, slug) values (39, 'Комедия', 37, 'genre-gzm-594');
insert into genre (id, name, parent_id, slug) values (40, 'Сценарий', 37, 'genre-iqc-715');
insert into genre (id, name, parent_id, slug) values (41, 'Драма, пьеса', 37, 'genre-rwb-020');