insert into tags (id, name, weight, slug) values (1, 'современная литература', 0, 'tag-vze-329');
insert into tags (id, name, weight, slug) values (2, 'классическая литература', 0, 'tag-sxx-751');
insert into tags (id, name, weight, slug) values (3, 'зарубежная литература', 0, 'tag-qph-175');
insert into tags (id, name, weight, slug) values (4, 'фэнтези', 0, 'tag-utu-640');
insert into tags (id, name, weight, slug) values (5, 'английская литература', 0, 'tag-efg-288');
insert into tags (id, name, weight, slug) values (6, 'русская литература', 0, 'tag-emb-796');
insert into tags (id, name, weight, slug) values (7, 'американская литература', 0, 'tag-mki-070');
insert into tags (id, name, weight, slug) values (8, 'фантастика', 0, 'tag-sfc-282');
insert into tags (id, name, weight, slug) values (9, 'детская литература', 0, 'tag-dok-592');
insert into tags (id, name, weight, slug) values (10, 'детектив', 0, 'tag-tvn-058');
insert into tags (id, name, weight, slug) values (11, 'любовь', 0, 'tag-hgl-811');
insert into tags (id, name, weight, slug) values (12, 'мистика', 0, 'tag-xci-098');
insert into tags (id, name, weight, slug) values (13, 'юмор', 0, 'tag-mhq-350');
insert into tags (id, name, weight, slug) values (14, 'приключения', 0, 'tag-pqh-443');
insert into tags (id, name, weight, slug) values (15, 'сказка', 0, 'tag-avr-577');
insert into tags (id, name, weight, slug) values (16, 'французская литература', 0, 'tag-ktt-578');
insert into tags (id, name, weight, slug) values (17, 'англия', 0, 'tag-zkr-024');
insert into tags (id, name, weight, slug) values (18, 'художественная литература', 0, 'tag-rjc-071');
insert into tags (id, name, weight, slug) values (19, 'психология', 0, 'tag-xcx-372');
insert into tags (id, name, weight, slug) values (20, 'философия', 0, 'tag-dxt-477');
insert into tags (id, name, weight, slug) values (21, 'экранизировано', 0, 'tag-rdi-425');
insert into tags (id, name, weight, slug) values (22, 'любимое', 0, 'tag-yvb-380');
insert into tags (id, name, weight, slug) values (23, 'антиутопия', 0, 'tag-lay-097');
insert into tags (id, name, weight, slug) values (24, 'роман', 0, 'tag-yoe-986');
insert into tags (id, name, weight, slug) values (25, 'франция', 0, 'tag-bcw-750');
insert into tags (id, name, weight, slug) values (26, 'дайте две', 0, 'tag-wou-018');
insert into tags (id, name, weight, slug) values (27, 'война', 0, 'tag-jem-220');
insert into tags (id, name, weight, slug) values (28, 'история', 0, 'tag-wxs-499');
insert into tags (id, name, weight, slug) values (29, 'флэшмоб 2016', 0, 'tag-mnv-181');
insert into tags (id, name, weight, slug) values (30, 'детство', 0, 'tag-mpb-748');
insert into tags (id, name, weight, slug) values (31, 'жизнь', 0, 'tag-szi-072');
insert into tags (id, name, weight, slug) values (32, 'драма', 0, 'tag-mst-334');
insert into tags (id, name, weight, slug) values (33, 'советская литература', 0, 'tag-fkg-610');
insert into tags (id, name, weight, slug) values (34, 'триллер', 0, 'tag-mrt-370');
insert into tags (id, name, weight, slug) values (35, 'школьная программа', 0, 'tag-lcu-349');
insert into tags (id, name, weight, slug) values (36, 'магия', 0, 'tag-ztl-444');