package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.NaturalId;

import javax.persistence.*;
import java.util.List;

@Getter
@Setter
@Entity
@ApiModel(description = "data model of author entity")
public class Author {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("image with the author's photo")
    private String photo;

    @NaturalId
    @Column(columnDefinition = "VARCHAR(255)", nullable = false, unique = true)
    @ApiModelProperty("mnemonic ID of the author, which will be displayed in the link to his page")
    private String slug;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("first and last name of the author")
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("description (biography, characteristics)")
    private String description;

    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Book2Author> books;
}
