package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@Table(name = "balance_transaction")
@ApiModel(description = "data model of balance transaction entity")
public class BalanceTransaction {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(columnDefinition = "TIMESTAMP", nullable = false)
    @ApiModelProperty("date and time of the transaction")
    private LocalDateTime time;

    @Column(columnDefinition = "INT DEFAULT 0", nullable = false)
    @ApiModelProperty("transaction size (positive — crediting, negative — debiting)")
    private Integer value;

    @Column(columnDefinition = "TEXT", nullable = false)
    @ApiModelProperty("transaction description: if crediting, then from where, if debiting, then to what")
    private String description;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "book_id", columnDefinition = "INT")
    private Book book;
}
