package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "book_file")
@ApiModel(description = "data model of book file entity")
public class BookFile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "type_id", columnDefinition = "INT", nullable = false)
    private BookFileType bookFileType;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("a random hash designed to identify the file when downloading")
    private String hash;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("file path")
    private String path;

    @ManyToOne
    @JoinColumn(name = "book_id", columnDefinition = "INT", referencedColumnName = "id", nullable = false)
    private Book book;
}
