package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "book_file_type")
@ApiModel(description = "data model of book file type entity")
public class BookFileType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("type file: PDF, EPUB, FB2")
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("description of file types")
    private String description;
}