package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "book_review")
@ApiModel(description = "data model of book review entity")
public class BookReview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "book_id", columnDefinition = "INT", nullable = false)
    private Book book;

    @Column(columnDefinition = "TIMESTAMP", nullable = false)
    @ApiModelProperty("the time when the review was left")
    private LocalDateTime time;

    @Column(columnDefinition = "TEXT", nullable = false)
    @ApiModelProperty("review text")
    private String text;

    @Column(columnDefinition = "INT DEFAULT 0", nullable = false)
    @ApiModelProperty("The rating of the review book, if the review book was not evaluated, is equal to 0")
    private Integer rating;

    @OneToMany(mappedBy = "bookReview", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<BookReviewLike> bookReviewLikes;

    public BookReview() {
        bookReviewLikes = new ArrayList<>();
    }
}
