package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "book2user_type")
@ApiModel(description = "data model of Book2UserType entity")
public class Book2UserType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("binding type code")
    private String code;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("the name of the binding type (Postponed — KEPT, In the basket — CART, Bought — PAID, Archived - ARCHIVED)")
    private String name;
}