package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "book_evaluation")
@ApiModel(description = "data model of book evaluation entity")
public class BookEvaluation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT")
    private User user;

    @ManyToOne
    @JoinColumn(name = "book_id", columnDefinition = "INT", nullable = false)
    private Book book;

    @Column(columnDefinition = "INT2 DEFAULT 0", nullable = false)
    @ApiModelProperty("the value of the book's rating is from 1 to 5")
    private byte value;
}
