package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.NaturalId;

import javax.persistence.*;

@Getter
@Setter
@Entity
@ApiModel(description = "data model of document entity")
public class Document {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(name = "sort_index", columnDefinition = "INT DEFAULT 0", nullable = false)
    @ApiModelProperty("the serial number of the document (to display on the document list page)")
    private Integer sortIndex;

    @NaturalId
    @Column(columnDefinition = "VARCHAR(255)", nullable = false, unique = true)
    @ApiModelProperty("mnemonic code of the document displayed in the link to the document page")
    private String slug;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("name of the document")
    private String title;

    @Column(columnDefinition = "TEXT", nullable = false)
    @ApiModelProperty("the text of the document in HTML format")
    private String text;
}
