package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "file_download")
@ApiModel(description = "data model of fileDownload entity")
public class FileDownload {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "book_id", columnDefinition = "INT", nullable = false)
    private Book book;

    @Column(columnDefinition = "INT DEFAULT 1", nullable = false)
    @ApiModelProperty("number of downloads")
    private Integer count;
}