package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@ApiModel(description = "data model of message entity")
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(columnDefinition = "TIMESTAMP", nullable = false)
    @ApiModelProperty("date and time the message was sent")
    private LocalDateTime time;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT", nullable = false)
    private User user;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("the user's email address, if he was not authorized")
    private String email;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("the user's name, if he was not authorized")
    private String name;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("subject of the message")
    private String subject;

    @Column(columnDefinition = "TEXT", nullable = false)
    @ApiModelProperty("message text")
    private String text;
}
