package com.example.bookshopapp.model;

import com.example.bookshopapp.model.enums.ContactType;
import com.example.bookshopapp.model.enums.PostgresSQLEnumType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@TypeDef(name = "pgsql_enum", typeClass = PostgresSQLEnumType.class)
@ApiModel(description = "data model of UserContact entity")
public class UserContact {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT", nullable = false)
    private User user;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "contact_type")
    @Type(type = "pgsql_enum")
    @ApiModelProperty("contact type (phone or e-mail)")
    private ContactType type;

    @Column(columnDefinition = "INT2", nullable = false)
    @ApiModelProperty("is the contact confirmed (0 or 1)")
    private byte approved;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("confirmation code")
    private String code;

    @Column(name = "code_trials")
    @ApiModelProperty("number of attempts to enter the confirmation code")
    private Integer codeTrials;

    @Column(name = "code_time", columnDefinition = "TIMESTAMP")
    @ApiModelProperty("date and time when the confirmation code was generated")
    private LocalDateTime codeTime;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("contact (e-mail or phone)")
    private String contact;
}
