package com.example.bookshopapp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@Table(name = "yoo_cash_operation")
@ApiModel(description = "data model of YooCash operation entity")
public class YooCashOperation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", columnDefinition = "INT", nullable = false)
    private User user;

    @Column(name = "operation_id", columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("Yoo cash id transaction")
    private String operationId;

    @Column(name = "idempotency_key", columnDefinition = "VARCHAR(255)", nullable = false)
    private String idempotencyKey;

    @Column(columnDefinition = "VARCHAR(255)")
    private String sum;

    @Column(columnDefinition = "TIMESTAMP")
    private LocalDateTime time;

    @Column(columnDefinition = "VARCHAR(255)")
    private String status;

    @Column(name = "payment_method", columnDefinition = "VARCHAR(255)")
    private String paymentMethod;
}
